# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: "daily"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "JohannesKnecht"
    multi-ecosystem-group: "all-dependencies"

  - package-ecosystem: "npm"
    directory: "frontend/AnkiAICardCreationFrontend"
    schedule:
      interval: "daily"
    reviewers:
      - "JohannesKnecht"
    multi-ecosystem-group: "all-dependencies"

  - package-ecosystem: "uv"
    directory: "backend/AnkiAICardCreationToolboxBackend"
    schedule:
      interval: "daily"
    reviewers:
      - "JohannesKnecht"
    multi-ecosystem-group: "all-dependencies"

  - package-ecosystem: "docker"
    directories:
      - "backend/AnkiAICardCreationToolboxBackend"
      - "frontend/AnkiAICardCreationFrontend"
    schedule:
      interval: "daily"
    reviewers:
      - "JohannesKnecht"
    multi-ecosystem-group: "all-dependencies"
