# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

groups:
  all-dependencies:
    applies-to: version-updates
    patterns:
      - "*"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "JohannesKnecht"

  - package-ecosystem: "npm"
    directory: "frontend/AnkiAICardCreationFrontend"
    schedule:
      interval: "daily"
    reviewers:
      - "JohannesKnecht"

  - package-ecosystem: "uv"
    directory: "backend/AnkiAICardCreationToolboxBackend"
    schedule:
      interval: "daily"
    reviewers:
      - "JohannesKnecht"

  - package-ecosystem: "docker"
    directories:
      - "backend/AnkiAICardCreationToolboxBackend"
      - "frontend/AnkiAICardCreationFrontend"
    schedule:
      interval: "daily"
    reviewers:
      - "JohannesKnecht"
