# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "frontend/AnkiAICardCreationFrontend"
    schedule:
      interval: "daily"
    reviewers:
      - "JohannesKnecht"
    groups:
      all-npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "backend/AnkiAICardCreationToolboxBackend"
    schedule:
      interval: "daily"
    reviewers:
      - "JohannesKnecht"
    groups:
      all-uv-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "backend/AnkiAICardCreationToolboxBackend"
    schedule:
      interval: "daily"
    reviewers:
      - "JohannesKnecht"
    groups:
      all-docker-backend-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "frontend/AnkiAICardCreationFrontend"
    schedule:
      interval: "daily"
    reviewers:
      - "JohannesKnecht"
    groups:
      all-docker-frontend-dependencies:
        patterns:
          - "*"

