version: '3'

tasks:
  build-backend:
    cmds:
      - task: build-image
        vars:
          DOCKER_IMAGE: ankiaicardcreationtoolboxbackend
          DOCKER_FILE_PATH: backend/AnkiAICardCreationToolboxBackend/Dockerfile
          CONTEXT_PATH: backend/AnkiAICardCreationToolboxBackend/

  build-frontend:
    cmds:
      - task: build-image
        vars:
          DOCKER_IMAGE: ankiaicardcreationtoolboxfrontend
          DOCKER_FILE_PATH: frontend/AnkiAICardCreationFrontend/Dockerfile
          CONTEXT_PATH: frontend/AnkiAICardCreationFrontend/

  run-backend:
    cmds:
      - task: run
        vars:
          DOCKER_IMAGE: ankiaicardcreationtoolboxbackend
          DOCKER_FILE_PATH: backend/AnkiAICardCreationToolboxBackend/Dockerfile
          CONTEXT_PATH: backend/AnkiAICardCreationToolboxBackend/

  run-frontend:
    cmds:
      - task: run
        vars:
          DOCKER_IMAGE: ankiaicardcreationtoolboxfrontend
          DOCKER_FILE_PATH: frontend/AnkiAICardCreationFrontend/Dockerfile
          CONTEXT_PATH: frontend/AnkiAICardCreationFrontend/


  lint-backend:
    dir: backend/AnkiAICardCreationToolboxBackend
    cmds:
      - uv run ruff check --fix .
      - uv run ruff format .

  build-image:
    internal: true
    cmds:
      - docker build -t {{.DOCKER_IMAGE}} -f {{.DOCKER_FILE_PATH}} ./{{.CONTEXT_PATH}}

  run:
    internal: true
    cmds:
      - docker rm -f {{.DOCKER_IMAGE}} 2>/dev/null
      - docker run --name {{.DOCKER_IMAGE}} -p 8080:8080 {{.DOCKER_IMAGE}}
